### ISSUE TITLE
Incorrect File::Slurper "write" method being called

### ISSUE THREAD

**Issue by tommystanton** [ironcamel/App-p#20]
Thank you for App::p! :smile:

I see that File::Slurper was used in App::p v0.0400.

Unfortunately, the wrong File::Slurper method is being called by App::p for the `w` bareword.  This can result in an error such as:

```text
Can't locate object method "write_file" via package "File::Slurper" at -e line 3.
```

The method that should be called is `write_text` ("text", not "file").  The `r` bareword works fine, though. :wink:

**Comment by ironcamel** [comment]
Thanks for catching this.  I will try to fix this soon.  Also, feel free to send me a PR if you want.
